//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_LavApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class detalle_servicio
    {
        [Display(Name = "Id Detalle Servicio")]
        public int id_detalle_servicio { get; set; }

        [Display(Name = "Id Servicio")]
        public int id_servicio { get; set; }

        [Display(Name = "Id tipo Servicio")]
        public int id_tipo_servicio { get; set; }

        [Display(Name = "Valor Servicio")]
        public decimal imp_valor_servivio { get; set; }

        [Display(Name = "Valor Descuento")]
        public decimal imp_valor_descuento { get; set; }

        [Display(Name = "Valor Neto")]
        public decimal imp_valor_neto { get; set; }

        [Display(Name = "Valor Iva")]
        public decimal imp_valor_iva { get; set; }

        [Display(Name = "Activo")]
        public Nullable<int> id_estado { get; set; }
    
        public virtual estado_servicio estado_servicio { get; set; }
        public virtual registro_servicio registro_servicio { get; set; }
        public virtual tipo_servicio tipo_servicio { get; set; }
    }
}
