//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_LavApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class persona_vehiculo
    {
        public int id_usuario_vehiculo { get; set; }
        public int id_persona { get; set; }
        public int id_vehiculo { get; set; }
        public string txt_observaciones { get; set; }
        public System.DateTime fec_asociacion { get; set; }
    
        public virtual personas personas { get; set; }
        public virtual vehiculos vehiculos { get; set; }
    }
}
