//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_LavApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class persona_vehiculo
    {

        [Display(Name = "Id Usuario Vehiculo")]
        public int id_usuario_vehiculo { get; set; }

        [Display(Name = "Id Persona")]
        public int id_persona { get; set; }

        [Display(Name = "Id Vehiculo")]
        public int id_vehiculo { get; set; }

        [Display(Name = "Observaciones")]
        public string txt_observaciones { get; set; }

        [Display(Name = "Fecha Asociación")]
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime fec_asociacion { get; set; }

        public virtual personas personas { get; set; }
        public virtual vehiculos vehiculos { get; set; }
    }
}
