//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_LavApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class registro_servicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public registro_servicio()
        {
            this.detalle_servicio = new HashSet<detalle_servicio>();
        }
    
        public int id_servicio { get; set; }
        public Nullable<int> id_persona { get; set; }
        public int id_tipo_documento { get; set; }
        public string txt_documento_cliente { get; set; }
        public string txt_nombre_cliente { get; set; }
        public string txt_apellido1_cliente { get; set; }
        public string txt_apellido2 { get; set; }
        public Nullable<int> id_vehiculo { get; set; }
        public System.DateTime fec_ingreso { get; set; }
        public Nullable<System.DateTime> fec_retiro { get; set; }
        public int id_usuario_atiende { get; set; }
        public string txt_observacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_servicio> detalle_servicio { get; set; }
        public virtual personas personas { get; set; }
        public virtual tipo_documento tipo_documento { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
