//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_LavApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class reserva_servicio
    {

        [Display(Name = "Id Reserva")]
        public int id_reserva { get; set; }

        [Display(Name = "Nombre")]
        public string txt_nombre { get; set; }

        [Display(Name = "Documento")]
        public int cedula { get; set; }

        [Display(Name = "Email")]
        [DataType(DataType.EmailAddress)]

        public string txt_email { get; set; }

        [Display(Name = "Teléfono")]
        [DataType(DataType.PhoneNumber)]
        public double telefono { get; set; }

        [Display(Name = "Vehículo ")]
        public int id_vehiculo { get; set; }

        [Display(Name = "Fecha Servicio")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime fecha_servicio { get; set; }

        [Display(Name = "Hora Servicio")]
        [DataType(DataType.Time)]
        [DisplayFormat(DataFormatString = "{0:HH:mm}", ApplyFormatInEditMode = true)]
        public System.DateTime hora_servicio { get; set; }

        [Display(Name = "Empleado")]
        public int id_usuario_atiende { get; set; }

        [Display(Name = "Observación")]
        public string txt_observacion { get; set; }

        [Display(Name = "Fecha Servcio")]
        public string Fecha_Servcio_Full 
        {
            get
            {
                return $"{fecha_servicio.ToString("yyyy-MM-dd")} {hora_servicio.ToString("HH:mm")}";
            }
        }

        public string hora_txt 
        {
            get 
            {
                return hora_servicio.ToString("HH:mm");
            }
        }
    
        public virtual usuarios usuarios { get; set; }
        public virtual vehiculos vehiculos { get; set; }
    }
}
