//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_LavApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class reserva_tipo_servicio
    {
        [Display(Name = "Tipo Servicio")]
        public int id_tipo_servicio { get; set; }

        [Display(Name = "Total Servicios Solicitados")]
        public int total_servicios_sol { get; set; }

        [Display(Name = "Id Cita Tipo Reserva")]
        public int id_cita_tipo_reserva { get; set; }

        [Display(Name = "Id Reserva")]
        public int id_reserva { get; set; }
    
        public virtual tipo_servicio tipo_servicio { get; set; }
        public virtual reserva_servicio reserva_servicio { get; set; }
    }
}
