//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_LavApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class roles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public roles()
        {
            this.usuario_rol = new HashSet<usuario_rol>();
        }
        
        [Display(Name = "Id Rol")]
        public int id_rol { get; set; }

        [Display(Name = "Descripción Rol")]
        public string txt_desc_rol { get; set; }

        [Display(Name = "Es Admon")]
        public bool sn_admin { get; set; }

        [Display(Name = "Es Empleado")]
        public bool sn_empleado { get; set; }

        [Display(Name = "Es Cliente")]
        public bool sn_cliente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuario_rol> usuario_rol { get; set; }
    }
}
