//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_LavApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tipo_servicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tipo_servicio()
        {
            this.detalle_servicio = new HashSet<detalle_servicio>();
        }

        [Display(Name = "Id Tipo Servicio")]
        public int id_tipo_servicio { get; set; }

        [Display(Name = "Descripción Servicio")]
        public string txt_desc_servicio { get; set; }

        [Display(Name = "Valor Servicio")]
        public decimal imp_valor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_servicio> detalle_servicio { get; set; }
    }
}
